#:schema node_modules/wrangler/config-schema.json
name = "sublink-worker1"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "f1eff4909a394c86bd7f673492e58f8f" }
]

[assets]
directory = "./public"
